

services:
  db:
    image: postgres:16
    
    env_file:
      - ./settings/prod.env
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      target: base
    env_file:
      - ./settings/prod.env
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
    command: ["uvicorn", "run_app:main_app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build:
      context: .
      target: worker
    env_file:
      - ./settings/prod.env
    depends_on:
      - rabbitmq
    command: ["celery", "-A", "backend.celery_app.create_app.celery_app", "worker", "-l", "INFO"]

  frontend:
    image: node:22-alpine
    working_dir: /app/frontend
    volumes:
      - ./:/app
    env_file:
      - ./settings/prod.env
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "5173:5173"
    command: sh -c "npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - api

volumes:
  db_data:


