route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://backend:8000/health/rabbitmq'
        send_resolved: true
